import type { Metadata } from 'next';
import '@/style/globals.css';

// fonts
import { geistSans, geistMono } from '@/public/fonts';
import { Provider } from '@/components/common/Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
